### ISSUE TITLE
Add sorting controls to per-country page too

### ISSUE THREAD

**Issue by ivan-aksamentov** [hodcroftlab/covariants#105]
Followup of #28 #77 #99 

Currently, the "per-variant" page contains a dropdown and a checkbox which both control the sorting options of the plot tooltips.

We might also add the same functionality to the "per-country" page, for symmetry.

Related: #104

**Comment by emmahodcroft** [comment]
I think we have this now, right? Or am I misunderstanding the request?

**Comment by ivan-aksamentov** [comment]
It's about this "Tooltip sort by" widget
![01](https://user-images.githubusercontent.com/9403403/143289361-c8b0bc2c-a00c-4439-8d3a-4644143b50ee.png)
We only have it on one page, but not the other. The proposal is to add it to the other page. May or may not be needed. Will require some work.

**Comment by emmahodcroft** [comment]
Ahhh I see. Hm, Interesting. I think sorting the tooltips on Per Country makes less intrinsic sense - we'd probably want to reorder the whole graph if we changed the tool-tip order. (Since the Per Country lines are always 'layered' and never cross (as it's cumulative), it kind of makes less sense for the tip labels to change order from the graph.)

**Comment by emmahodcroft** [comment]
is same as #28
