### ISSUE TITLE
Link to build for 20B/S.484K doesn't work

### ISSUE THREAD

**Issue by theosanderson** [hodcroftlab/covariants#122]
The link on https://covariants.org/variants/S.E484 to https://nextstrain.org/groups/neherlab/ncov/S.E484?c=gt-S_484&f_clade_membership=20B/S.484K&label=clade:20B/S.484K&p=grid&r=country yields an error `The label 'clade' value '20B/S.484K' was not found in the tree - no zoom performed`. If I try to zoom in manually the URL produced gives the same error. I have made a PR that seems to do the filtering correctly: https://github.com/hodcroftlab/covariants/pull/121 but the zoom still doesn't work.

**Comment by emmahodcroft** [comment]
Thank you for catching this @theosanderson! I looked into #121 and I figured out the issue. I renamed my `clades` defining file to try and give everyone the 'proper' Nextstrain names - so that included changing things like `20B/S.484K` (note the dot) to `20B/S:484K` (note the colon). 

Unfortunately, I didn't then update any of the URLS! But it also seems like the zooming URL functionality doesn't play nice with the `:` . So, I think the best option for me here to preserve all the functionality is to go back to using `.` for the clade labels.

I've fixed this in my local files, and I hope to do another full run early next week, which should re-name these memberships & labels & fix the URLS! 

I really appreciate you catching this though!

**Comment by theosanderson** [comment]
Awesome! Thanks a lot for explaining and sorry to bother your weekend!

**Comment by emmahodcroft** [comment]
Not at all - I appreciate your catching the brokenness and the chance to fix it!

**Comment by ivan-aksamentov** [comment]
Colon is not a valid URL character. The URL containing colons has to be [URLencoded](https://en.wikipedia.org/wiki/Percent-encoding). For hardcoded URLs I usually use Sublime Text. Can also be done programmatically on Python or JS side.

**Comment by emmahodcroft** [comment]
This seems to be working again now! Thanks again for flagging this @theosanderson !
