### ISSUE TITLE
Layman's names for variants

### ISSUE THREAD

**Issue by Toerag1** [hodcroftlab/covariants#140]
Not being a virologist, I'd like to see the common 'layman's names' for variants e.g 'Kent','Brazil', 'South African' & 'Bristol'.  It would help disseminate what the mainstream media are talking about.

**Comment by emmahodcroft** [comment]
Hi @Toerag1 - thanks for this suggestion. On some of the variant pages there is some reference to where the variant was first identified, but in general in the scientific community we really try to refrain from using 'Geographic names' for the variants. While I recognise that they've arisen due to lack of other easy and memorable names, and are commonly used by the mainstream media, they can be inaccurate (we often do not know where a variant arose, just where it was first detected or first became prevalent) and can be very harmful to the image of countries. This can, for example, discourage countries from reporting variants. So, at CoVariants I am trying to avoid those 'geographic names'.
