### ISSUE TITLE
2 week interval periods date

### ISSUE THREAD

**Issue by lucasrodes** [hodcroftlab/covariants#195]
Hi,
First of all, thanks for putting this resource available to the public. We started using it on our platform at https://ourworldindata.org/covid-cases#coronavirus-sequences-by-variant.

I have a minor doubt regarding the `date` values in [perCountryData.json](https://github.com/hodcroftlab/covariants/blob/master/web/data/perCountryData.json). Take the case of the US. There are entries reported for the 28th of June. On your website, you label this as the 2-week interval Jun 28 - Jul 12, even if, as of today, there are 4 days left for the 12th of July.

I would really appreciate it if you could shed some light on this.

Thank you once again for all your hard work and time invested in this resource (and others).

---

#### US Example (data point 2021-06-28)

```
{
  "cluster_counts": {
    "20A.EU2": 0.0,
    "20A/S:126A": 0.0,
    "20A/S:439K": 0.0,
    "20A/S:98F": 0.0,
    "20B/S:732A": 0.0,
    "20E (EU1)": 0.0,
    "20H (Beta, V2)": 0.0,
    "20I (Alpha, V1)": 1.0,
    "20J (Gamma, V3)": 2.0,
    "21A (Delta)": 57.0,
    "21B (Kappa)": 0.0,
    "21C (Epsilon)": 0.0,
    "21D (Eta)": 0.0,
    "21F (Iota)": 0.0,
    "21G (Lambda)": 0.0,
    "21H": 0.0,
    "S:677H.Robin1": 0.0,
    "S:677P.Pelican": 0.0
  },
  "total_sequences": 61,
  "week": "2021-06-28"
}
```

Australia

**Comment by emmahodcroft** [comment]
Hi @lucasrodes ! Thanks for letting me know that you're using the data on Our World in Data - I'm a huge fan of what you guys do - so I'm super-glad if it's useful. 

Regarding the question about the dates: So, each 2-week period is pre-defined, and we don't dynamically change these so that they only reflect dates "not in the future". But of course, for any dates that are beyond the current date, we won't have data for those. 

It would be neat (and a little more intuitive) to have date panel for the 'last mouseover' point adjust to reflect the current date (or update date), but I'm afraid I don't think this is something we have the bandwidth to implement in the near future - CoVariants is something both me and the web dev Ivan do very part-time! Hopefully this reassures you about the date periods though - for the last one, you can always cut this off on the current date (or last update date - see top-right corner of website) and you won't be losing any data. 

Just let me know if you have any other questions!

**Comment by lucasrodes** [comment]
Thanks for your words, @emmahodcroft, it is really nice to read 😄!

It all makes sense, I [just updated our scripts](https://github.com/owid/covid-19-data/commit/c462f41d632533fef373fc5b1362ede75890b4eb#diff-9cd2ec230429a6b2dbe2465a7b1786b1552a330624666bfb8d78a1a152b0aec7) to fix the last update date, thanks @ivan-aksamentov for the pointer.

We stay in touch!

**Comment by emmahodcroft** [comment]
Hey @lucasrodes - There must be a better way to reach out! But, I wanted to warn you I'm about to push up a new format of data, which will split 21A Delta into 21J and 21I Delta - subclades recognised by Nextstrain now. (These aren't thought to be epidemiologically significant, but they are quite distinct & widespread phylogenetically.) If you want to continue to just show 'Delta' you can put 21A, 21J and 21I together and graph them as one. I hope this doesn't catch anything on your end off-guard!

**Comment by lucasrodes** [comment]
Hi @emmahodcroft,
Thanks for your kind message!

Will take a look so our pipeline does not break. In the future, may tweak our data to display these subvariants on our website (feels like now almost 100% is Delta).

As per reaching out, feel free to ping me on Twitter (twitter.com/lucasrodesg) or via [mail](lucas@ourworldindata.org).

Thanks once again for your work 😄

**Comment by emmahodcroft** [comment]
Great, thanks for the extra contact info - I've put that in my address book! I am hoping to add a couple more variants in the near future - but I'm really stretched for time, so it might be more like next month 🙃 . I'll try to give another heads-up if more 'subsets of Delta' start appearing, so you can consider how to handle them!
