### ISSUE TITLE
Add Delta-Plus

### ISSUE THREAD

**Issue by anjali-gopinathan** [hodcroftlab/covariants#196]
With all the [concern in the media](https://www.cnn.com/2021/06/25/health/delta-plus-variant-explainer-intl-hnk-scn/index.html) about the Delta-Plus variant (AY.1 or B.1.617.2.1), it would be helpful to see its spread in different countries displayed on the per-country charts.

**Comment by emmahodcroft** [comment]
Thanks for the suggestion @anjali-gopinathan ! At the moment, though any 'Delta Plus' isn't tracked in the graphs, there is a dedicated focal build showing sequences that are Delta but also have the 417N mutation [here](https://nextstrain.org/groups/neherlab/ncov/21A.Delta.S.K417). Because of downtime on our cluster, this is a little old now, but I'm starting new builds today.

As you can see in that build, 'Delta Plus' isn't a very meaningful name - there are actually 2 clusters that are Delta + 417N (AY.1 and AY.2), but also a number of individual sequences. Because these are separate phylogenetically, I would need add a separate variant for AY.1 and AY.2.

At the moment, the total number of sequences that are Delta + 417N is about 500 - assuming that's split evenly between AY.1 and AY.2, that's about 250 each. That's a pretty small number compared to most of the other variants I track, so that's why it hasn't been added yet. However, I'm keeping an eye on these clusters, and if they continue to grow, I will consider adding them as tracked variants!
