### ISSUE TITLE
Omicron Last Data Point

### ISSUE THREAD

**Issue by maximeLpt** [hodcroftlab/covariants#232]
Hi All,
Thanks for this tool, I just wanted to understand why in this repo we just have 7 cases for South Africa vs 114 in the GISAID website https://www.gisaid.org/hcov19-variants/

Best Regards
ML

**Comment by emmahodcroft** [comment]
HI @maximeLpt ! I'm really glad the site has been useful. The reason for the difference in the case numbers is because there's been a delay in our datasource from GISAID, likely due to the increased pressure from traffic around Omicron. This is back up and working now, so I'll be updating CoVariants as soon as possible - unfortunately it takes about 12 hours for the data to process before I can get it up online!

**Comment by maximeLpt** [comment]
Hi @emmahodcroft thanks for your prompt answer. Do you store somewhere the timeseries for each variants?
Have a great day
ML

**Comment by emmahodcroft** [comment]
Hi Maxime, Yes, if you look in `web/data/` on this Github, you'll find the data for the PerCluster and PerCountry pages. Hope that helps!
