### ISSUE TITLE
More information about the omicron variant

### ISSUE THREAD

**Issue by Amin-Sharifan** [hodcroftlab/covariants#236]
According to this recent ScienceInsider article (link: https://www.science.org/content/article/where-did-weird-omicron-come), omicron appears to be distinct compared with other SARS-CoV-2 variants (i.e., alpha, beta, etc) in terms of its original formation. In other words, omicron seems to be the oldest among the SARS-CoV-2 variants and yet it was detected just a week ago as of writing this issues. Though its detection was recent, its original existence seems to date back to the early 2020. Is this concept worth mentioning in the CoVariants under the heading "Variant: 21K (Omicron)"?

**Comment by emmahodcroft** [comment]
Dear @Amin-Sharifan  - thanks so much for this information and link! However, since we still know very little about the variant origins (it's mostly guessing at the moment), I'm going to not mention it for the time, and see if we learn more in the future, with more confidence. Thank you for all the great link suggestions though, I really appreciate them!
