### ISSUE TITLE
Forward schedule

### ISSUE THREAD

**Issue by maximeLpt** [hodcroftlab/covariants#238]
Hi All,

I hope you are doing well.
Could you give us the forward schedule of sequences update by country?

Best Regards

**Comment by emmahodcroft** [comment]
Hi @maximeLpt - I'm afraid I don't understand your question? I'm currently updating CoVariants daily. However, the time it takes to process the sequences means I run about 36~ hours behind what you can see on GISAID at the current moment. As soon as a country puts new sequences on GISAID, you can generally expect them to be reflected in the numbers on CoVariants charts about 36 hours later.

Note that in 'more normal times' I update CoVariants about twice a week - currently I'm prioritizing running every day to keep things updated due to the interest & fast-changing landscape of Omicron.
