### ISSUE TITLE
Wrong data for the Netherlands

### ISSUE THREAD

**Issue by SanderNielen** [hodcroftlab/covariants#250]
The website shows 100% Omicron in the Netherlands. This seems to contradict information from official sources. See e.g. https://coronadashboard.government.nl/landelijk/varianten.

**Comment by emmahodcroft** [comment]
Hi @SanderNielen, thanks for writing! The current CoVariants shows that, for the last data point, Netherlands only has 50 sequences and these are all Omicron, that's why it's showing up 100%. However, the Netherlands has been recently turning in about 3000 sequences in a two week period - so the data is still incoming, and one must interpret percentages derived from small numbers of sequences very carefully! As more data comes in, it's likely this percentage will decrease. I've just pushed the Christmas Eve update, and Netherlands now has 69 sequences, with 75% Omicron (should be live momentarily).
