### ISSUE TITLE
Feature request: Drill down into "others" and low-frequency variants.

### ISSUE THREAD

**Issue by BioTurboNick** [hodcroftlab/covariants#253]
When I see "Other" sticking around in South Africa, I'm curious what those are. I'm also curious to see if any minor variants are managing to hang around at low frequencies for a long time.

The graphs make it easy to see what's dominant, but if something could be done to raise visibility for the minor variants, that would be useful.

**Comment by emmahodcroft** [comment]
This is a great question @BioTurboNick, but a difficult one to address! The 'other' category can be real mix of other sequences, meaning it's difficult to show how to represent them, at least in the existing graphs, as there would be too many colours/lines to make the graphs readable.

However the idea is interesting, if we could come up with another way to open some other tab or panel to display what makes up 'other' perhaps in terms of Pango lineages. 

Currently, I don't actually store the group of 'other' sequences (they are just the number that don't fall into one of the CoVariant Variants), so I'd need to adjust the scripts to store these to access more information about them, then come up with a visual way on the website to display this somehow. It's an interesting idea and I'm happy to keep it in mind, but due to lack of resources at the moment I'm afraid it's not likely something that'll come quickly, unfortunately!
