### ISSUE TITLE
Multiple reports per date and country

### ISSUE THREAD

**Issue by lucasrodes** [hodcroftlab/covariants#257]
Hi team,
As always, thanks for your incredible work.

We have detected that for some weeks and countries, there are two entries registered in [perCountryData.json](https://github.com/hodcroftlab/covariants/blob/master/web/data/perCountryData.json) file. 

In particular for `week=2021-01-27` and `country ∈ {Germany, Japan, Brazil, Australia, United States, Poland and Bangladesh}`.

<details><summary><b>An example for Bangladesh</b></summary>
<p>

In this example, I load the `perCountryData.json` file, and filter to obtain only the last three entries for Bangladesh. We note that the last two entries have the same value for 'week'.

```python
# Read remote file
>>> from urllib.request import urlopen
>>> import json
>>> url = "https://github.com/hodcroftlab/covariants/raw/master/web/data/perCountryData.json"
>>> response = urlopen(url)
>>> data_raw = json.loads(response.read())
# Keep only global data
>>> data = data_raw["regions"][0]["distributions"]
# Filter only Bangladesh data
>>> data_bangladesh = [d for d in data if d["country"]=="Bangladesh"][0]["distribution"]
# Print last 3 entries
>>> data_bangladesh[-3:]
[{'cluster_counts': {'20H (Beta, V2)': 0.0,
   '20I (Alpha, V1)': 0.0,
   '20J (Gamma, V3)': 0.0,
   '21A (Delta)': 0.0,
   '21D (Eta)': 0.0,
   '21I (Delta)': 1.0,
   '21J (Delta)': 34.0,
   '21K (Omicron)': 8.0},
  'total_sequences': 43,
  'week': '2021-12-13'},
 {'cluster_counts': {'20H (Beta, V2)': 0.0,
   '20I (Alpha, V1)': 0.0,
   '20J (Gamma, V3)': 0.0,
   '21A (Delta)': 0.0,
   '21D (Eta)': 0.0,
   '21I (Delta)': 0.0,
   '21J (Delta)': 1.0,
   '21K (Omicron)': 7.0},
  'total_sequences': 8,
  'week': '2021-12-27'},
 {'cluster_counts': {'20H (Beta, V2)': 0.0,
   '20I (Alpha, V1)': 0.0,
   '20J (Gamma, V3)': 0.0,
   '21A (Delta)': 0.0,
   '21D (Eta)': 0.0,
   '21I (Delta)': 0.0,
   '21J (Delta)': 1.0,
   '21K (Omicron)': 2.0},
  'total_sequences': 3,
  'week': '2021-12-27'}]
```

</p>
</details>

Thanks!

**Comment by emmahodcroft** [comment]
Thank you for spotting this @lucasrodes !! 

This looks like it's an old bug come back to bite me - as all good bugs are. We noticed that dates went funny last year in the switch from 2020 to 2021, and I decided then that 'funny' (one 1-week interval amongst the 2-week intervals) wasn't enough to pursue, so put it off - since it wouldn't happen again until next year!

Well, here we are --- thanks past Emma!

The issue here lies in my attempt to go from using ISO weeks to store data into using 2-week intervals to display the data - ISO weeks don't always neatly convert into 2-week intervals, since the last week of the year always needs to be 52 or 53 but the first week always needs to be 1 - there may not be "two weeks between them" if that makes sense.

Here, dates that dates that fall in "Week 1" of 2022 (`2022-01-04`) end up being stored as 'week 0' by my code. They should be part of the previous 2-week interval (so, week 52 of 2021), but end up as 'week 0'.

During data processing I store everything by ISO week (easier) - but `2021 52` and `2022 0` are not the same... so the data gets put into two buckets instead of 1. When this gets converted back to dates, later - they both end up being converted to `2021-12-27` - which is technically correct - that's the time period they should be part of! However, since they were put into two buckets, they're already 'separate' at this point - nothing would combine them.

So, we end up with two datapoints with the same date - technically not wrong, as I said - but not actual functional datapoint code :)

I'm implementing a bugfix that should detect this odd scenario and force these 'week 0' dates to be officially part of the previous date period, which should take care of this!

**Comment by emmahodcroft** [comment]
Hi @lucasrodes - good news, I think we've got a fix working now, that's live! Thank you again for pointing this out so we could get it tidied up properly :)

If you're curious, the two commits that fix this are:
https://github.com/hodcroftlab/covariants/commit/7373a2923a525f6c433fc6b15616d81eb60a89f2
(The main fix)
https://github.com/hodcroftlab/covariants/commit/7705f658c09f463b936137c54dcbfc52442112e7
(Me realising I do this in two more places, so have to apply the fix _everywhere_ 🙃 )

**Comment by lucasrodes** [comment]
Thanks for the rapid action (my reaction emoji "🚀" is very accurate here)! Also for the explanation, very appreciated.
Everything working like a charm on our end now. 

I have had so many bugs due to ISO week and other date formatting issues... seems hard to master 😄!
