### ISSUE TITLE
What is the meaning of cluster_sequences?

### ISSUE THREAD

**Issue by wanglu2014** [hodcroftlab/covariants#273]
There were four columns in cluster_tables directory ("total_sequences","cluster_sequences","unsmoothed_cluster_sequences","unsmoothed_total_sequences").
They related to the case number of patients infected by a specific variant. However, what is the difference of biological meaning between unsmoothed and total sequence?
Thank you for your help!

**Comment by emmahodcroft** [comment]
Hi @wanglu2014 - importantly these aren't cases, these are just sequences - the numbers of cases is likely higher for any country. In the file you're looking at, these are sequence counts for a variant, by the date period given. The columns `total_sequences` and `cluster_sequences` are smoothed - they have an [algorithm applied](https://github.com/hodcroftlab/covariants/blob/master/scripts/helpers.py#L31) to smooth the counts so that the graphs look less jagged. 
The `unsmoothed_` files are the raw counts without any smoothing applied - just the counts themselves. I hope that helps!

**Comment by wjdiadijai** [comment]
I have the same problem that's been bothering me. Does total_sequences means the number of total_sequences detected by the country. for example, On April 27,2020, India total_sequences is 74, that means India only detected 74 sequences？
Or to change the question, what is a sequence? 74 sequences means the variant has 74 sub-clade?
Thank you for your help!I look forward to hearing from your response.

**Comment by emmahodcroft** [comment]
The `total_sequenecs` means the total number of sequences detected and shared by that country. Early in the pandemic, before sequencing was widespread, it's very possible these numbers are low. It's also possible that more sequences were done, but perhaps were not shared. However, it's important to remember that almost no country sequences every case. 

In this case, "sequence" means one genetic sequence of the SARS-CoV-2 virus, which was isolated from a patient swab.
I hope that helps!
