### ISSUE TITLE
More descriptive page titles

### ISSUE THREAD

**Issue by azizLIGHT** [hodcroftlab/covariants#288]
Many pages have a nondescriptive title 'CoVariants'. 

Pages like Home, Variants, Per country, Per variant, Shared Mutations, and Acknowledgements all have a HTML title of `<title>CoVariants</title>`, with the exception of the FAQ page, which is titled `<title>CoVariants: FAQ</title>`. 

Please consider using more descriptive page titles, like how the FAQ page currently is, for all the other pages, so that browser tabs can have useful titles and browsing can be done easier.

**Comment by ivan-aksamentov** [comment]
This is implemented, but someone needs to take time and fill-in the content here:

https://github.com/hodcroftlab/covariants/blob/2f2f26715e126798ccb2fcac283a137c32b5914e/web/src/seo/seoMetadata.ts#L18-L24

Contributions are very welcome!

**Comment by azizLIGHT** [comment]
That's what I saw as well but wasn't sure because it seems a little 'hard-coded'. 

How can I use the already existing title of the page that exists in the content, and add it to <title>?

For example, /per-country has a in-page <h1 class="PageHeading-sc-1380ypn-0 gStIVs">Overview of Variants in Countries</h1> and that should be the title for this page probably. How can I refer to that title programmatically in <title> inside  seoMetadata.ts. I would like to avoid writing it out manually in seoMetadata.ts, in case the title in <h1> changes, then you have a different and old title inside seoMetadata.ts that will have to be changed again manually.

**Comment by ivan-aksamentov** [comment]
I guess you could extract the existing titles into variables or into a map, and then import into both places.

Alternatively, instead of this centralized solution with a map and `Document` component, one could use the `Head` component on every page instead: https://nextjs.org/docs/api-reference/next/head. This way the SEO things would be in close proximity to the content. I haven't explored this solution, there might be drawbacks as well.

Feel free to play with different approaches and try different things if you have time.

**Comment by emmahodcroft** [comment]
This was another post-Christmas PR that I missed entirely - sorry!
Something that auto-updates would be a nice touch! However in the meantime, I updated these manually.  See #289
