### ISSUE TITLE
Remember country/variant filter state in the URL params

### ISSUE THREAD

**Issue by ivan-aksamentov** [hodcroftlab/covariants#30]
We might synchronize the filter checkboxes on the sidebar of plot pages with URL query params.

This would allow:

 - sharing filtered views of these pages
 - bookmarking

which might facilitate sharing, discussion and tracking the information of interest for users.

For example, we might have a `countries` and `variants` params as follows

```
/per-country?countries=France,Germany,Italy&variants=20A.EU1,20A.EU2
```

Navigating to this URL would render the "Per country" page with only France, Germany and Italy and 20A.EU1 and 20A.EU2 variants enabled in filters.

and if user further unchecks 20A.EU1 and Italy and adds Latvia, then the URL in their address bar will become:

```
/per-country?countries=France,Germany,Latvia&variants=20A.EU2
```

**Comment by emmahodcroft** [comment]
I think this would be very cool to have for linking to particular countries in particular, on Per Country page. Or for a state on the USA version of the page - etc.
How hard would this be to implement, is it a really biggie? (I feel like it might be)
I'd be happy to start with just showing the displayed set of countries/regions (not saving URL state for the variants selected).

**Comment by emmahodcroft** [comment]
Coming back to this because just got a request from someone on Twitter.

**Comment by ivan-aksamentov** [comment]
Yes, this will require moving internals around quite a bit. Not immediate. I might try it sometimes.

**Comment by an-ko-7** [comment]
Hey Ivan, I'm the one who spoke with Emma. Since I've got some experience on web dev and time, I could take a shot. I've got it running offline and I've got the basic structure of the project. Any specific tips?

**Comment by ivan-aksamentov** [comment]
Hi @an-ko-7,

How I imagine it:

You'd need to change the `places` state here:
https://github.com/hodcroftlab/covariants/blob/6d7d642ccb43a7f54911b9bf09f95e23a0c1d2ff/web/src/components/CountryDistribution/CountryDistributionPage.tsx#L37
depending on what query params are, and vice versa.

I'd probably use the Next.js native `useRouter()` to get and set URL params. And/or perhaps also a query string library. I think we might already have one in the dependencies.

There is a few things that make things complicated:

 - `continents` and `countries` depend on each other within `places` state, so you need to remember to update both when one have changed. There are `toggleContinent()` and   `toggleCountry()` helper functions which handle checkbox events. For URL params you might need new version of these functions that toggle multiple countries/continents.

 - The Region selector (World/USA/Switzerland). Even if you implement this feature for "World" countries it's unclear what should happen with the other 2 regions. Perhaps region should also be a URL param. Perhaps "World" should be default if omitted. Decisions are to be made.

If you proceed with contribution, I suggest you to create a draft PR early on, so that Vercel bot could deploy it automatically and you could discuss with Emma how it looks and feels, by example.

I am currently busy on something else. But ping me if you need help.

**Comment by emmahodcroft** [comment]
>Perhaps region should also be a URL param. Perhaps "World" should be default if omitted. Decisions are to be made.
I would be happy with this this implementation! I think good to put region as a URL param as well, if possible.

**Comment by an-ko-7** [comment]
Thanks @ivan-aksamentov, I got time to try it out today. 

I found that changing the `places` state here is not that handy:
https://github.com/hodcroftlab/covariants/blob/6d7d642ccb43a7f54911b9bf09f95e23a0c1d2ff/web/src/components/CountryDistribution/CountryDistributionPage.tsx#L37
This state loads everything on the page, including the `countryDistributionComponents` to toggle countries. So, if initially only one country is loaded, it's not possible to load more. To change this behavior I'd have to make in depth changes to the project's structure.

I thought of the _Our World In Data_ platform, where the whole dataset is loaded initially, and only the data that the user selected is shown. So, I'm thinking of doing the same here: loading all the `places` and only making visible the selected ones. 

If you agree, that's where I would like your advice, since I'm not that experienced in React. Where would you put this toggle, for it to take place just before the DOM loads? I know about `ComponentDidMount` on other projects, but this one seems to be using a different structure.

**Comment by ivan-aksamentov** [comment]
@an-ko-7 

> [...] only one country is loaded, it's not possible to load more [...]
> [...] I'm thinking of doing the same here: loading the data of all the countries and only making visible the selected data.

All countries are already loaded and their `enabled` field is set to a value from `region_country.json` file, which Emma generates. If URL params are present, you need to set all of the countries to `enable: false`, except for those that are in the URL params. The `enable` flag is what controls the checkboxes and presence of plots. Here is the type for a country:

https://github.com/hodcroftlab/covariants/blob/6d7d642ccb43a7f54911b9bf09f95e23a0c1d2ff/web/src/io/getPlaces.ts#L8

and the data is loaded just below it. I think making a loop over countries on `initialPlaces` before it is passed to `useState()` hook is your best bet.


> I know about ComponentDidMount on other projects, but this one seems to be using a different structure.

Yes, we use React Hooks, which is the best practive nowadays. Class-based components are mostly dead, except for very narrow use-cases:

 - https://reactjs.org/docs/react-component.html#the-component-lifecycle

If you want to understand the codebase and be able to modify it, then you'd need to brush up on react hooks. Here are some links to the official docs:

 - https://reactjs.org/docs/hooks-overview.html
 - https://reactjs.org/docs/hooks-intro.html
 - https://reactjs.org/docs/hooks-reference.html

I am quite busy on another project right now, so could not contribute my self. Let me know if you need more info.

**Comment by an-ko-7** [comment]
Thanks for the info. I tried the looping you suggested with a modified `getPerCountryData` function, and the problem I described comes up. As you can see on the bottom left corner [of this screenshot](https://imgur.com/a/zY6S3Wc), only the 2 countries I requested show up in the distribution component, so the user can't see more countries to enable.
I know that all the data is loading in the production implementation and I meant that I'm thinking of keeping it like this, and not only requesting the data for a few new countries each time another is selected.
Sorry if you're suggesting some use of `initialPlaces` that I don't get.

**Comment by ivan-aksamentov** [comment]
@an-ko-7 Maybe you are removing (filtering) the country entries from the result? You need to preserve them all and just toggle `.enable`. You cannot load some of the countries. The JSON is imported and bundled along with the code, so there is no point to filter or remove the entries. 

In any case, feel free to submit a draft PR and we could look at what's happening. I might misremember things too.

**Comment by an-ko-7** [comment]
@ivan-aksamentov you're right, I was filtering out the other countries instead of making their `enable` attribute `false`. Now a proof-of-principle works, I'll update it a bit more and upload on a draft PR as you said.

**Comment by emmahodcroft** [comment]
@an-ko-7 Thank you so much for this! The two examples with the World & US are working beautifully and it's really cool to see a way to load specific graphs. 

I had some trouble loading some of the links -- after a few minutes on a page it often freezes, not sure why. I think it might be very resource intensive? My laptop fan is kicking in.
I suppose there's not yet been work on the check-boxes - I couldn't get either the variant ones or the country ones to work - but this may just not be "wired in" yet! When I tried these, the page froze. Also, it seemed that just expanding the 'Countries' panel to the left also freezes the page.

I think it's fine that if linking to no country or two a non-existent region that the World loads as default - and same if they link to a correct region but some nonsense, it loads the whole thing. 
A more complicated use-case might be what happens if some countries are valid but others aren't. Is it possible to parse out the good from the bad? Currently it seems to just load the whole region (same as if one country is provided and it's bad). 
It might also be good to clear the URL bar in these cases (down to region level).

I'm easy between either using the current country names or 3 letter abbreviations. I can see that the upside of using country names is that they match what people can see (some countries codes are not intuitive!) - but then you have to deal with spaces. On the other hand, the 3 letter codes are clean, tight, and regulated - but less intuitive.


But I think the concept here is great, and it's really cool to see it working to load up a few countries!

**Comment by an-ko-7** [comment]
Thanks @emmahodcroft . Yes, updating the URL only with the valid countries is easy. For the abbreviations, I'm thinking of leaving it with full names for now, because it's not clear what should be the choices for the other regions beside `World`. 
I fixed a couple minor coding points as well, but before uploading another draft, I'd like some input from @ivan-aksamentov; particularly for the freezing issue and if it shows up with Vercel in general, or if I should look for some bug.

**Comment by ivan-aksamentov** [comment]
Hi @an-ko-7,

The freezing might be due to infinite loops, either the plain for or while loops or more obscure insider React, for example "state change -> rerender -> state-change -> rerender -> ..." loop. You might be doing something wrong in the component code.

I tried to review the PR code, but it has 177 files changed in the diff, so I was not able to.

Cannot help much more that that right now, because I am busy on another project, sorry.

**Comment by emmahodcroft** [comment]
I'm not a github wizz by any definition, but to clean up the `diff` - you could remove all the files in `cluster_tables`, `content` and `scripts` and `web/data`. This are all the updates I'm doing more regularly so reflect your branch going out of sync with master, but shouldn't be relevant for your PR (though of course we can check this right before merging).

I don't know if there's a git-savvy way to do this, but this should then help narrow it down to the files you've _actually_ changed, which might help Ivan take a look! :D

**Comment by an-ko-7** [comment]
OK, my last version works with the feature Emma requested. For example, [here the user requests](https://covariants-70q16hicl-hodcroftlab.vercel.app/per-country?countries=Greece~Random~Italy) the countries "Greece, Random, Italy" and only the first and third load.

As for the 177 files, yes, by accident I fetched all the recent data on the project, but I only changed 3 coding files. You can have a quick look [with these filters](https://github.com/hodcroftlab/covariants/pull/240/files?authenticity_token=JqV%2F8YWuGcIvRRsxkJeJa8fDlEjFHjV1UV0nZwHgbI9Ou7mCPsAGmrnkNndFjSQJrofmtX%2FyO62XUPcogcWvfQ%3D%3D&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx) on the coding changes (except the first file, _MutationBadge.tsx_, which was fetched as well).

As for the freezing, with a `console.log` I see that indeed it gets stuck in a loop when the user tries to toggle anything on this page: a country, a continent, a region, a variant. Strange, can't figure what can be causing this, but I'm suspecting some quirk of React that I'm not familiar with.

@ivan-aksamentov I understand you're busy and thanks for your time until now; if you can, have a look on the above Github link, perhaps you can find it quickly with your experience. But I'll figure it out eventually.

**Comment by an-ko-7** [comment]
[I think it's fixed now](https://covariants-fnbtgyj91-hodcroftlab.vercel.app/per-country?region=World&countries=Greece~Poland~Rand), it seems that the `useEffect` for `initialPlaces` didn't need a second argument, [change here](https://github.com/hodcroftlab/covariants/pull/240/commits/7142627f331acf3b7766fca9498e67f561750af7). (To be noted, it's is in production code, don't know why it's not causing issues there.) Will do some more testing tomorrow.

**Comment by ivan-aksamentov** [comment]
Let's keep discussion in the PR (https://github.com/hodcroftlab/covariants/pull/240), so that we don't need to jump between 2 places.
