### ISSUE TITLE
Please add TSV file format for the USA states variant tables file

### ISSUE THREAD

**Issue by BethPathak** [hodcroftlab/covariants#324]
Dear Emma:

We would be very appreciative if you could duplicate the Jul 3 (and future) JSON file and also release it in TSV format.

Many thanks,
Beth Pathak

**Comment by emmahodcroft** [comment]
Dear @BethPathak - thank you for your message! I'm afraid I won't be releasing the files in TSV format, as the file sizes are already quite large, and duplicating them would take up more space for the repository and updates. However, the JSON file for the USA is available in two slightly different JSON formats - some people find [this file](https://github.com/hodcroftlab/covariants/blob/master/cluster_tables/USAClusters_data.json) format easier to parse (this file contains just USA state data). The [other file](https://github.com/hodcroftlab/covariants/blob/master/web/data/perCountryData.json) contains all the data - look for the part of the JSON that is `region: United States`.

There are many JSON libraries available that can help you parse JSON files into whatever format you find most useful. I know JSON can not always be the easiest format, but it's incredibly machine friendly, which is why we use it. I'd suggest giving the first file (USA only) a look - it's a little more straightforward in layout and may be easier for you to transform.
I hope that helps!
