### ISSUE TITLE
How to interpret mutations on spike pos. 493

### ISSUE THREAD

**Issue by a-qvecell** [hodcroftlab/covariants#379]
Hello :)
Thank you for a really useful page! 
I am a little confused as to how to interpret the mutations on spike position 493 as they are listed here:
https://covariants.org/shared-mutations
Here, we see both S:Q493R, S:Q493Q and S:R493Q.
My intuition regarding the table is that the first amino acid mentioned for each mutation would be Wuhan-hu-1, here Q, changed to R in e.g. Omicron BA.1. 
When I then read S:Q493Q, I imagine that this mutation must have reverted but in another position in the codon. 
But when I then see S:R493Q, I start thinking if all initial positions are relative to the variant that the clade in question arises from.

I hope you can help me understand the table - thank you in advance :)
Best,
Amanda

**Comment by emmahodcroft** [comment]
Hi Amanda @a-qvecell - I'm so sorry about this confusion! You're right, this isn't very clear. In general, I always list mutations relative to ancestral (Wuhan). However, sometimes I try to convey more information (for better or worse). For example, here in 22E this is a reversion from the S:Q493R that happened in ancestor 21L. 

What made this doubly confusing is that usually I try to ensure on the variant page anything like this is explained a bit, but for 22E this is completely missing. I'll add to the text so that this is explained for those who look for it, but I recognise that it's still a bit confusing. I'm not sure the best way to handle this going forward - I'll try to have a think about whether there's a better way to convey this information!

Thanks for alerting us that it's not clarified anywhere, though - at least I can try to make it more clear on the variant page!

Best,
Emma

**Comment by a-qvecell** [comment]
Hi Emma, 
Thank you for clarifying.
Just to make sure I get this right: 
The reversion Q493Q is on the same nucleotide and 22E looks like Wuhan on all the nucleotides of this codon. 
R493Q in the XBB variants are also just back to Wuhan and can be disregarded when listing mutations relative to this reference, you just want to convey that they look different from their ancestor?
Also thank you for your quick reply :) 
Best, 
Amanda
